num1=float(input("Enter the number1:"))
num2=float(input("Enter the number2:"))
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)
print(num1 ** num2)
print("Is num1 greater than num2?" , num1>num2)
print("Is num1 equal to num2?" ,num1==num2 )
print("Is num1 less that num2?" , num1<num2)